// Mocks generated by Mockito 5.4.6 from annotations
// in your_budget_manager/test/core/security/pin_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:your_budget_manager/core/security/secure_key_storage.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SecureKeyStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureKeyStorage extends _i1.Mock implements _i2.SecureKeyStorage {
  MockSecureKeyStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveKey(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#saveKey, [key, value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getKey, [key]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> deleteKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#deleteKey, [key]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
